{{- if and .Values.secrets.externalSecrets.enabled .Values.secrets.externalSecrets.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "plex-linker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "plex-linker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
