{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fullnameOverride | default "organizr-tab-controller" }}
  labels:
    app.kubernetes.io/name: organizr-tab-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnameOverride | default "organizr-tab-controller" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.fullnameOverride | default "organizr-tab-controller" }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
