{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride | default "organizr-tab-controller" }}
  labels:
    app.kubernetes.io/name: organizr-tab-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
