apiVersion: v2
name: plex-linker
description: Plex Linker v3 â€” web app to symlink Radarr movies to Sonarr TV specials and sync Plex watch state. External Postgres.
type: application
version: 3.0.0
appVersion: "3.0.0"
kubeVersion: ">=1.22.0-0"
keywords:
  - plex
  - sonarr
  - radarr
  - symlink
  - web
maintainers: []
dependencies:
  - name: onepassworditem
    version: "1.0.0"
    repository: https://expectedbehaviors.github.io/OnePasswordItem-helm
