{{- if .Values.cleanup.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qbittorrent-jobs.fullname" . }}-cleanup
  labels:
    app.kubernetes.io/name: qbittorrent-jobs
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $k, $v := .Values.cleanup.configMaps.cleanup.data }}
  {{ $k | quote }}: {{ $v | quote }}
{{- end }}
{{- end }}
